[build]
  publish = "."

[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200

[forms]
  [forms.submissions]
    notifications = [
      { event = "submission", type = "email", email = "connect@cadautomator.com" }
    ]
